### ISSUE TITLE
论文中的地址失效

### ISSUE THREAD

**Issue by ResistWu** [SuperSuperSuperSuper5/How-to-process-KDD-99-dataset#1]
您好~
      您 [论文.docx] 一文中的github地址已经失效，请问其中的代码地址SuperSuperSuperSuper5就是当前地址Jayzisinstance吗？
      thx.
![](http://p08f7olbl.bkt.clouddn.com/kdd.JPG)

**Comment by rikonaka** [comment]
https://github.com/Jayzisinstance/How-to-process-KDD-99-dataset/blob/master/%E8%AE%BA%E6%96%87.docx
就是这个啦~

**Comment by ResistWu** [comment]
thx!
还有一个问题，请问kdd_pyspark.py中的这段代码
`if __name__ == "__main__":
    if (len(sys.argv) != 3):
        print("Usage: /home/spark-1.6.1-bin-hadoop2.4/bin/spark-submit --driver-memory 2g " + "KDD_spark.py max_k corrected")
        sys.exit(1)`
其中的sys.argv是什么意思呢？我每次运行到这里就会print这一行然后中止
或者说这几行包含sys.argv的main函数是希望实现什么功能呢？（实在搞不懂了TUT）
` if (len(sys.argv) != 3):
        print("Usage: /home/spark-1.6.1-bin-hadoop2.4/bin/spark-submit --driver-memory 2g " + "KDD_spark.py max_k corrected")
        sys.exit(1)
    # set up environment
    max_k = int(sys.argv[1])
    data_file = sys.argv[2]
    conf = SparkConf().setAppName("kdd-cup-99")
    sc = SparkContext(conf=conf)`
麻烦您了！！十分感谢！！

**Comment by rikonaka** [comment]
这个好像是pyspark的内置函数吧，它函数需要两个参数作为入参，然后你要给足了才能运行
