### ISSUE TITLE
sys.argv参数的问题

### ISSUE THREAD

**Issue by ResistWu** [SuperSuperSuperSuper5/How-to-process-KDD-99-dataset#2]
您好，
因为没有在代码中找到sys.argv[0]而在主函数的判断中sys.argv是需要3个参数的，所以想问一下sys.argv[0]是用来做什么的？

**Comment by rikonaka** [comment]
sys.argv[0]是程序的名字，啊，请问你说的是哪个代码里面的？

**Comment by ResistWu** [comment]
谢谢你！我聚出来啦！但是结果跟您文档中的不太一样，我设置max_k=30时最佳k值是20，merge之后只有12个cluster，您的文档中有19个；max_k=60时最佳k值是40，merge之后也只有24个cluster,不同于您文档中的45个（不包括null cluster的话）。p.s. 我用的10%数据集
而且。。。<论文.doc>中聚类结果表下的"k=30,维度=41"中的维度是什么意思。。。实在没有领悟到QUQ
而且还有一个问题~我最后运行出来的结果是这样的，只有聚类结果没有代表攻击数/非代表攻击数这些值，不知是不是没有运行statistic_result的原因（因为在您的github中没有找到，不知能否指点或添加一下><
![](http://p08f7olbl.bkt.clouddn.com/%E6%8D%95%E8%8E%B7.JPG)

**Comment by rikonaka** [comment]
@ResistWu 啊哈哈，出来了就好～～～
